# Generated by Django 3.1 on 2025-03-25 04:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
                ('colors', django.db.models.manager.Manager()),
            ],
        ),
    ]
